(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LumiereCore=api})(typeof self!=='undefined'?self:this,function(){
  function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
  function searchLocal(books,query,category='All'){const q=norm(query),c=norm(category);return books.filter(b=>(!q||norm(`${b.title} ${b.author} ${b.category||''} ${(b.subjects||[]).join(' ')} ${b.id}`).includes(q))&&(!c||c==='all'||norm(b.category).includes(c)||norm((b.subjects||[]).join(' ')).includes(c)))}
  function gutenbergId(value){const s=String(value||'');const m=s.match(/(?:ebooks\/|ebook:|etext)(\d+)/i)||s.match(/\b(\d{1,7})\b/);return m?Number(m[1]):null}
  function epubUrl(id,images=true){if(!Number.isInteger(Number(id))||Number(id)<1)return null;return `/gutenberg/cache/epub/${Number(id)}/pg${Number(id)}${images?'-images':''}.epub`}
  function coverUrl(id){return `/gutenberg/cache/epub/${Number(id)}/pg${Number(id)}.cover.medium.jpg`}
  function parseOpds(xml){if(typeof DOMParser==='undefined')return[];const doc=new DOMParser().parseFromString(xml,'application/xml');return [...doc.querySelectorAll('entry')].map(e=>{const title=e.querySelector('title')?.textContent?.trim()||'Untitled';const author=e.querySelector('author name')?.textContent?.trim()||'Unknown author';const id=gutenbergId(e.querySelector('id')?.textContent)||gutenbergId([...e.querySelectorAll('identifier')].map(x=>x.textContent).join(' '));const links=[...e.querySelectorAll('link')];const epub=links.find(x=>(x.getAttribute('type')||'').includes('epub'))?.getAttribute('href');const cover=links.find(x=>(x.getAttribute('rel')||'').includes('image'))?.getAttribute('href');const subjects=[...e.querySelectorAll('category')].map(x=>x.getAttribute('term')).filter(Boolean);if(!id&&!epub)return null;return{id:id||title,title,author,category:subjects[0]||'Gutenberg',subjects,language:'en',source:'Project Gutenberg OPDS',cover:cover||coverUrl(id),epub:epub||epubUrl(id,true),epubNoImages:epubUrl(id,false),text:id?`/gutenberg/cache/epub/${id}/pg${id}.txt`:null}}).filter(Boolean)}
  function dedupe(books){const m=new Map();for(const b of books){const k=norm(`${b.title}|${b.author}`);if(!m.has(k))m.set(k,b)}return [...m.values()]}
  return{norm,searchLocal,gutenbergId,epubUrl,coverUrl,parseOpds,dedupe}
});